apiVersion: apps/v1
kind: Deployment
metadata:
  name: channel
  labels:
    app: channel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: channel
  template:
    metadata:
      labels:
        app: channel
    spec:
      containers:
        - name: channel
          image: sachingoyaldocker/baat-org-channel:latest
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_HOST
              value: "channel-db"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "channel"
            - name: DATABASE_USER
              value: "channel"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_INITIALIZATION_MODE
              value: "always"
          ports:
            - containerPort: 8080
          imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: channel
  labels:
    app: channel
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: channel
  type: ClusterIP
